dist: trusty
sudo: required
language: node_js
node_js:
- '8'
addons:
  chrome: stable
before_install:
- wget "http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip"
- unzip chromedriver_linux64.zip -d $HOME/bin
- export PATH=$PATH:$HOME/bin
- npm i -g yarn
install:
- npm i -g codecov
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
- yarn && yarn test:cov && yarn start-and-e2e